export const SERVICES_DATA = {
  haircut: {
    slug: 'haircut',
    category: 'HAUTE COIFFURE',
    title: 'Bespoke Precision Haircut & Sculpting',
    tagline: 'Architectural hair sculpting tailored to your facial bone structure and natural organic movement.',
    heroImage: 'https://images.unsplash.com/photo-1562322140-8baeececf3df?auto=format&fit=crop&q=80&w=1600',
    duration: '60 MIN',
    price: 'Starting at ₹3,500',
    maintenance: 'Every 4–6 Weeks',
    suitableFor: 'All Hair Textures, Densities & Lengths',
    overview: {
      includes: 'Complete 1-on-1 facial architecture analysis, diagnostic hair sectioning, bespoke precision haircutting, custom blow-dry, and structural finishing.',
      forWho: 'Discerning individuals seeking a refined, weightless haircut engineered specifically for their individual bone structure and growth direction.',
      expectedResults: 'A clean, effortlessly movable silhouette that maintains its architectural form even weeks after leaving the atelier.',
    },
    process: [
      { step: '01', title: 'Consultation & Mapping', desc: 'Analyzing facial bone angles, crown growth patterns, and lifestyle identity.' },
      { step: '02', title: 'Scalp & Follicle Diagnostic', desc: 'Assessing hair elasticity, density, and moisture balance.' },
      { step: '03', title: 'Precision Sculpting', desc: 'Executing wet and dry ergonomic sectioning tailored to head anatomy.' },
      { step: '04', title: 'Structural Blow-Dry', desc: 'Diffusing and heat-shaping to enhance natural weightless movement.' },
      { step: '05', title: 'Final Refinement', desc: 'Dry-texturizing, edge refinement, and bespoke shine serum application.' },
    ],
    benefits: [
      { title: 'Bone Structure Harmony', desc: 'Cut lines designed to complement cheekbones and jawline contour.' },
      { title: 'Weightless Movement', desc: 'Internal sectioning removing bulk without thinning hair density.' },
      { title: 'Effortless Styling', desc: 'Falls naturally into place with minimal daily maintenance.' },
    ],
    gallery: [
      'https://images.unsplash.com/photo-1562322140-8baeececf3df?auto=format&fit=crop&q=80&w=1200',
      'https://images.unsplash.com/photo-1560869713-7d0a29430803?auto=format&fit=crop&q=80&w=1200',
      'https://images.unsplash.com/photo-1519699047748-de8e457a634e?auto=format&fit=crop&q=80&w=1200',
    ],
    faqs: [
      { q: 'How often should I get a precision haircut?', a: 'We recommend returning every 4 to 6 weeks to maintain pristine perimeter lines and structural weight balance.' },
      { q: 'Is a consultation included?', a: 'Yes, every session begins with an unhurried 15-minute diagnostic analysis before cutting.' },
    ],
  },
  color: {
    slug: 'color',
    category: 'COLOR ATELIER',
    title: 'Couture Balayage & Tone Formulation',
    tagline: 'Hand-painted dimensional balayage and organic gloss enhancement customized to skin undertones.',
    heroImage: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&q=80&w=1600',
    duration: '150 MIN',
    price: 'Starting at ₹8,500',
    maintenance: 'Every 8–12 Weeks',
    suitableFor: 'Natural, Color-Treated & Multi-Tonal Hair',
    overview: {
      includes: 'Skin undertone diagnostic, customized clay balayage painting, bond-building treatment, bespoke gloss toner, and couture blow-dry.',
      forWho: 'Clients looking for sun-kissed, dimensional hair color with seamless blend and zero harsh regrowth lines.',
      expectedResults: 'Luminous, multidimensional color with rich reflection and preserved fiber integrity.',
    },
    process: [
      { step: '01', title: 'Undertone Diagnostic', desc: 'Matching color pigments to warm, cool, or neutral skin complexions.' },
      { step: '02', title: 'Clay Lightening', desc: 'Hand-painting freehand strokes for soft, seamless gradation.' },
      { step: '03', title: 'Bond Reconstitution', desc: 'Infusing amino acids to protect cuticles during processing.' },
      { step: '04', title: 'Organic Tone Gloss', desc: 'Neutralizing brassiness and enhancing mirror reflection.' },
      { step: '05', title: 'Haute Finish', desc: 'Applying thermal protection and soft waves to highlight dimension.' },
    ],
    benefits: [
      { title: 'Seamless Regrowth', desc: 'Soft root transition requiring low touch-up maintenance.' },
      { title: 'Custom Shade Blend', desc: 'Purity pigments blended exclusively for your complexion.' },
      { title: 'Fiber Protection', desc: 'Bond-reconstituting formulas preserving hair strength.' },
    ],
    gallery: [
      'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&q=80&w=1200',
      'https://images.unsplash.com/photo-1492106087820-71f1a00d2b11?auto=format&fit=crop&q=80&w=1200',
      'https://images.unsplash.com/photo-1560869713-7d0a29430803?auto=format&fit=crop&q=80&w=1200',
    ],
    faqs: [
      { q: 'Will balayage damage my natural hair?', a: 'Our clay lighteners and bond-reinforcing elixirs ensure your cuticles remain smooth and healthy.' },
      { q: 'How long does the service take?', a: 'Plan for approximately 2.5 to 3 hours for a complete balayage, gloss, and styling experience.' },
    ],
  },
  spa: {
    slug: 'spa',
    category: 'RESTORATIVE RITUAL',
    title: 'European Botanical Scalp & Follicle Therapy',
    tagline: 'Deep restorative scalp therapy utilizing essential botanical elixirs and micro-steam infusion.',
    heroImage: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&q=80&w=1600',
    duration: '75 MIN',
    price: 'Starting at ₹4,000',
    maintenance: 'Bi-Weekly or Monthly',
    suitableFor: 'Dry, Stressed, Scalp-Sensitive or Thinning Hair',
    overview: {
      includes: 'Tricho-microscope scalp analysis, customized essential oil blend, warm botanical steam, acupressure massage, and cold water rinse.',
      forWho: 'Anyone experiencing scalp tightness, seasonal dryness, or stress-related hair fatigue seeking pure relaxation.',
      expectedResults: 'A detoxified, purified scalp environment promoting healthy follicle vitality and silk softness.',
    },
    process: [
      { step: '01', title: 'Tricho Scalp Scan', desc: 'Analyzing pore congestion and scalp moisture levels under 200x magnification.' },
      { step: '02', title: 'Exfoliating Scrub', desc: 'Applying sea salt scrub to gently purge impurity buildup.' },
      { step: '03', title: 'Botanical Steam Infusion', desc: 'Deep-penetrating essential oils under controlled warm mist.' },
      { step: '04', title: 'Acupressure Massage', desc: '15-minute cranial pressure-point massage boosting blood flow.' },
      { step: '05', title: 'Silk Blowout', desc: 'Gentle drying leaving hair light, fragrant, and voluminous.' },
    ],
    benefits: [
      { title: 'Scalp Purification', desc: 'Clears buildup and rebalances natural sebum production.' },
      { title: 'Stress Relief', desc: 'Deeply relaxing pressure-point massage easing tension.' },
      { title: 'Follicle Stimulation', desc: 'Promotes optimal conditions for healthy hair growth.' },
    ],
    gallery: [
      'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&q=80&w=1200',
      'https://images.unsplash.com/photo-1527799820374-dcf8d9d4a388?auto=format&fit=crop&q=80&w=1200',
      'https://images.unsplash.com/photo-1519699047748-de8e457a634e?auto=format&fit=crop&q=80&w=1200',
    ],
    faqs: [
      { q: 'Is this treatment suitable for sensitive scalps?', a: 'Yes, our formulations use organic plant extracts free from synthetic fragrances or harsh chemicals.' },
    ],
  },
  keratin: {
    slug: 'keratin',
    category: 'TEXTURE ARCHITECTURE',
    title: 'Silk Keratin Glass-Smoothing Infusion',
    tagline: 'Formaldehyde-free silk keratin smoothing formula sealing cuticles for long-lasting weightless shine.',
    heroImage: 'https://images.unsplash.com/photo-1519699047748-de8e457a634e?auto=format&fit=crop&q=80&w=1600',
    duration: '180 MIN',
    price: 'Starting at ₹9,000',
    maintenance: 'Every 3–5 Months',
    suitableFor: 'Frizzy, Unruly, Coarse or Humidity-Sensitive Hair',
    overview: {
      includes: 'Clarifying wash, silk protein infusion, precision titanium flat ironing, keratin seal, and sleek glass finish.',
      forWho: 'Individuals wanting frizz-free, manageable, high-shine hair that withstands humid weather.',
      expectedResults: 'Smooth, mirror-like hair with 80% reduced blow-dry time and zero frizz.',
    },
    process: [
      { step: '01', title: 'Clarifying Purge', desc: 'Opening cuticles to ensure maximum keratin absorption.' },
      { step: '02', title: 'Protein Infusion', desc: 'Comb-applying silk amino acids section by section.' },
      { step: '03', title: 'Blow-Seal', desc: 'Blow-drying protein into the inner hair cortex.' },
      { step: '04', title: 'Titanium Thermal Ironing', desc: 'Locking in smooth keratin bonds at precise temperatures.' },
      { step: '05', title: 'Glass Shine Finishing', desc: 'Final rinse and silk serum polish for liquid mirror shine.' },
    ],
    benefits: [
      { title: 'Frizz Defense', desc: '100% resistance against extreme tropical humidity.' },
      { title: 'Time Savings', desc: 'Cuts daily morning blow-dry time in half.' },
      { title: 'Formaldehyde Free', desc: 'Safe, non-toxic formulation gentle on scalp and lungs.' },
    ],
    gallery: [
      'https://images.unsplash.com/photo-1519699047748-de8e457a634e?auto=format&fit=crop&q=80&w=1200',
      'https://images.unsplash.com/photo-1492106087820-71f1a00d2b11?auto=format&fit=crop&q=80&w=1200',
      'https://images.unsplash.com/photo-1562322140-8baeececf3df?auto=format&fit=crop&q=80&w=1200',
    ],
    faqs: [
      { q: 'How long does silk keratin last?', a: 'With proper sulfate-free care, results last between 3 to 5 months.' },
    ],
  },
  bridal: {
    slug: 'bridal',
    category: 'BRIDAL HAUTE COIFFURE',
    title: 'Private Atelier Bridal & Crown Architecture',
    tagline: 'Bespoke bridal hair trial session, veil placement architecture, and customized couture styling.',
    heroImage: 'https://images.unsplash.com/photo-1580618672591-eb180b1a973f?auto=format&fit=crop&q=80&w=1600',
    duration: '120 MIN',
    price: 'Starting at ₹15,000',
    maintenance: 'Wedding Day & Event Rehearsals',
    suitableFor: 'Couture Brides & Royal Wedding Parties',
    overview: {
      includes: 'Private suite trial session, veil & dupatta placement engineering, hair extension seamless integration, and wedding day styling.',
      forWho: 'Brides looking for an exclusive, stress-free haute coiffure experience in private atelier luxury.',
      expectedResults: 'A majestic, photograph-perfect bridal crown that remains secure from ceremony to late reception.',
    },
    process: [
      { step: '01', title: 'Outfit & Jewelry Diagnostic', desc: 'Matching hair silhouette to necklines and headpieces.' },
      { step: '02', title: 'Trial Sculpting', desc: 'Testing 2-3 custom coiffure variations in private suite.' },
      { step: '03', title: 'Extension Integration', desc: 'Blending seamless remy hair for desired length and volume.' },
      { step: '04', title: 'Veil Engineering', desc: 'Securing heavy dupattas with discreet internal anchor pins.' },
      { step: '05', title: 'Wedding Day Execution', desc: 'Flawless day-of styling with 12-hour spray hold.' },
    ],
    benefits: [
      { title: 'VIP Suite Privacy', desc: 'Exclusive access to our private bridal suite for you and bridal party.' },
      { title: 'All-Day Hold', desc: 'Engineered pins and humidity spray holding up through dancing.' },
      { title: 'Photogenic Precision', desc: 'Coiffure designed to look breathtaking from 360 degrees.' },
    ],
    gallery: [
      'https://images.unsplash.com/photo-1580618672591-eb180b1a973f?auto=format&fit=crop&q=80&w=1200',
      'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=1200',
      'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&q=80&w=1200',
    ],
    faqs: [
      { q: 'How far in advance should I book my bridal session?', a: 'We recommend reserving your trial 2 to 3 months prior to your wedding date.' },
    ],
  },
  botox: {
    slug: 'botox',
    category: 'DEEP RECONSTRUCTION',
    title: 'Collagen & Amino Acid Hair Restructuring',
    tagline: 'Intensive molecular hair botox treatment restoring structural mass, elasticity, and brilliant mirror reflection.',
    heroImage: 'https://images.unsplash.com/photo-1492106087820-71f1a00d2b11?auto=format&fit=crop&q=80&w=1600',
    duration: '120 MIN',
    price: 'Starting at ₹10,500',
    maintenance: 'Every 2–3 Months',
    suitableFor: 'Bleached, Heat-Damaged or Over-Processed Hair',
    overview: {
      includes: 'Molecular hair mass scan, raw marine collagen infusion, infrared cold flat ironing, seal mask, and silk polish.',
      forWho: 'Clients with chemically compromised hair needing deep internal repair rather than surface smoothing.',
      expectedResults: 'Restored hair density, sealed split ends, and silky touchable softness.',
    },
    process: [
      { step: '01', title: 'Mass Diagnostic', desc: 'Evaluating cortex porosity and keratin loss.' },
      { step: '02', title: 'Collagen Masking', desc: 'Applying concentrated collagen & caviar extract.' },
      { step: '03', title: 'Infrared Cold Seal', desc: 'Utilizing ultrasound irons to drive nutrients deep.' },
      { step: '04', title: 'Cuticle Neutralizer', desc: 'Rinsing with cold acidic toner to lock in moisture.' },
      { step: '05', title: 'Mirror Finish', desc: 'Gentle blow-dry revealing supple, strong hair strands.' },
    ],
    benefits: [
      { title: 'Molecular Repair', desc: 'Fills broken keratin gaps inside damaged hair shafts.' },
      { title: 'Elasticity Restoration', desc: 'Prevents snapping and breakage during brush styling.' },
      { title: 'Intense Mirror Glow', desc: 'Reflects light evenly across smoothed hair cuticles.' },
    ],
    gallery: [
      'https://images.unsplash.com/photo-1492106087820-71f1a00d2b11?auto=format&fit=crop&q=80&w=1200',
      'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&q=80&w=1200',
      'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&q=80&w=1200',
    ],
    faqs: [
      { q: 'Is hair botox different from keratin?', a: 'Yes, hair botox focuses on deep internal structural reconstruction without straightening your natural curl pattern.' },
    ],
  },
};
