export const WORK_DATA = {
  'bridal-makeover': {
    slug: 'bridal-makeover',
    category: 'HAUTE BRIDE',
    title: 'Royal Heritage Bridal Transformation',
    clientName: 'Priya Sharma',
    timeTaken: '4.5 Hours',
    heroImage: 'https://images.unsplash.com/photo-1580618672591-eb180b1a973f?auto=format&fit=crop&q=80&w=1600',
    beforeImage: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=1000',
    afterImage: 'https://images.unsplash.com/photo-1580618672591-eb180b1a973f?auto=format&fit=crop&q=80&w=1000',
    clientStory: 'Priya came to Salman Hair Studio 8 weeks before her royal Rajasthan wedding. She wanted a regal, voluminous bridal coiffure that would support a heavy embroidered veil without flattening her crown.',
    hairAnalysis: {
      porosity: 'Medium Porosity',
      density: 'Fine Hair, Medium Density',
      problems: 'Lack of crown volume, dry heat-damaged ends from frequent styling, difficult dupatta anchoring.',
    },
    consultation: 'Salman Khan formulated a dual-phase strategy: a 4-week botanical scalp treatment ritual to build root spring, followed by seamless 22-inch remy hair extensions cut to blend with her natural layers.',
    process: [
      { step: '01', title: 'Consultation', desc: 'Matching coiffure volume to wedding jewelry and dupatta weight.' },
      { step: '02', title: 'Wash & Purge', desc: 'Clarifying wash with botanical jasmine oil mist.' },
      { step: '03', title: 'Treatment', desc: 'Intensive keratin collagen moisture mask for high-shine reflection.' },
      { step: '04', title: 'Cut & Seamless Blend', desc: 'Precision face-framing layers integrating hair extensions.' },
      { step: '05', title: 'Crown Styling', desc: 'Hot-pin curling and internal anchor pin placement.' },
      { step: '06', title: 'Final Reveal', desc: 'Securing royal veil with 12-hour humidity protection.' },
    ],
    productsUsed: ['Organic Jasmine Scalp Oil', 'Collagen Amino Elixir', 'Seamless Remy Extensions 22"', 'Haute Hold Veil Mist'],
    testimonial: 'Salman created absolute magic for my wedding day. My hair held its regal volume for 14 hours straight without a single pin shifting!',
  },
  'keratin-treatment': {
    slug: 'keratin-treatment',
    category: 'TEXTURE REFINEMENT',
    title: 'Silk Keratin Glass Glass-Smoothing Restoration',
    clientName: 'Rhea Kapoor',
    timeTaken: '3.0 Hours',
    heroImage: 'https://images.unsplash.com/photo-1519699047748-de8e457a634e?auto=format&fit=crop&q=80&w=1600',
    beforeImage: 'https://images.unsplash.com/photo-1560869713-7d0a29430803?auto=format&fit=crop&q=80&w=1000',
    afterImage: 'https://images.unsplash.com/photo-1519699047748-de8e457a634e?auto=format&fit=crop&q=80&w=1000',
    clientStory: 'Rhea suffered from extreme humidity frizz during Mumbai monsoons, making daily morning styling frustrating and time-consuming.',
    hairAnalysis: {
      porosity: 'High Porosity',
      density: 'Coarse, Unruly Wave Pattern',
      problems: 'Open cuticles, extreme frizz, split ends from daily blow-drying.',
    },
    consultation: 'A 100% formaldehyde-free silk protein keratin infusion was chosen to seal cuticles, restore internal protein mass, and impart liquid mirror shine.',
    process: [
      { step: '01', title: 'Consultation', desc: 'Porosity strand testing and cuticle analysis.' },
      { step: '02', title: 'Clarifying Purge', desc: 'Deep washing to remove product buildup and open cuticles.' },
      { step: '03', title: 'Keratin Infusion', desc: 'Section-by-section silk amino acid mask application.' },
      { step: '04', title: 'Precision Blow-Dry', desc: 'Diffusing protein deep into inner hair cortex.' },
      { step: '05', title: 'Titanium Thermal Seal', desc: 'Flat ironing at 210°C to lock keratin matrix.' },
      { step: '06', title: 'Glass Finish Reveal', desc: 'Cold water rinse and weightless silk serum polish.' },
    ],
    productsUsed: ['Silk Amino Keratin Mask', 'Thermal Guard Elixir', 'Organic Argan Polish'],
    testimonial: 'My morning blow-dry time went from 45 minutes to 5 minutes! My hair feels like liquid silk.',
  },
  'color-correction': {
    slug: 'color-correction',
    category: 'COUTURE COLOR',
    title: 'Champagne Balayage & Color Correction',
    clientName: 'Ananya Verma',
    timeTaken: '4.0 Hours',
    heroImage: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&q=80&w=1600',
    beforeImage: 'https://images.unsplash.com/photo-1492106087820-71f1a00d2b11?auto=format&fit=crop&q=80&w=1000',
    afterImage: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&q=80&w=1000',
    clientStory: 'Ananya had uneven home-dyed orange brassiness and harsh root lines from a previous botched color job at another salon.',
    hairAnalysis: {
      porosity: 'Uneven Porosity',
      density: 'Medium Density',
      problems: 'Banded brassy orange tones, dry porous mid-lengths.',
    },
    consultation: 'Master colorist Elena Rostova executed a corrective root melt and clay balayage painting to create seamless champagne dimension without bleach damage.',
    process: [
      { step: '01', title: 'Color Mapping', desc: 'Identifying brassy bands and target cool champagne tones.' },
      { step: '02', title: 'Gentle Purge Wash', desc: 'Removing superficial artificial color buildup.' },
      { step: '03', title: 'Clay Balayage', desc: 'Freehand painting lighter ribbons away from roots.' },
      { step: '04', title: 'Corrective Root Melt', desc: 'Blending dark natural roots seamlessly into balayage.' },
      { step: '05', title: 'Champagne Gloss', desc: 'Neutralizing warmth with violet-pearl toner.' },
      { step: '06', title: 'Editorial Blowout', desc: 'Soft waves revealing dimensional contrast.' },
    ],
    productsUsed: ['Clay Freehand Lightener', 'Violet-Pearl Tone Gloss', 'Bond Reconstituting Elixir'],
    testimonial: 'Elena completely rescued my hair! The brassiness is totally gone and the champagne tones look insanely expensive.',
  },
};

export const WORK_ITEMS = Object.entries(WORK_DATA).map(([id, item]) => ({
  id,
  ...item,
}));

